# Generated by Django 4.0.2 on 2022-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('koordinator', models.CharField(blank=True, max_length=100, null=True)),
                ('etkinlik_tarihi', models.DateTimeField()),
                ('duyuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('konum', models.CharField(blank=True, max_length=100)),
                ('aciklama', models.TextField()),
                ('icerik', models.CharField(blank=True, max_length=90)),
            ],
        ),
    ]
