# Generated by Django 4.0.2 on 2022-02-21 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okul_numara', models.CharField(max_length=10, null=True, unique=True)),
                ('telefon_numarasi', models.CharField(max_length=11, null=True, unique=True)),
                ('bolum', models.CharField(max_length=50, null=True)),
                ('sinif', models.CharField(choices=[('0', 'Hazırlık Sınıfı'), ('1', 'Birinci Sınıf'), ('2', 'İkinci Sınıf'), ('3', 'Üçüncü Sınıf'), ('4', 'Dördüncü Sınıf'), ('4+', '4+')], default=0, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
