# Generated by Django 4.0.2 on 2022-02-23 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_profil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etkinlik',
            new_name='EtkinlikModel',
        ),
        migrations.RenameModel(
            old_name='Profil',
            new_name='ProfilModel',
        ),
    ]
