# Generated by Django 4.0.2 on 2022-02-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_etkinlik_etkinlikmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilmodel',
            old_name='user',
            new_name='isim',
        ),
        migrations.AddField(
            model_name='profilmodel',
            name='hakkinda',
            field=models.CharField(blank=True, max_length=290, null=True),
        ),
        migrations.CreateModel(
            name='KitapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('yazarin_adi', models.CharField(blank=True, max_length=50, null=True)),
                ('verildigi_tarih', models.DateField(null=True)),
                ('alinacagi_tarih', models.DateField(null=True)),
                ('durum', models.BooleanField(default=True)),
                ('sahip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='kitaplar', to='website.profilmodel')),
            ],
        ),
    ]
